/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.customer.management.tool.ui.admin;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.context.support.ResourceBundleMessageSource;
import org.springframework.stereotype.Component;

import com.customer.management.tool.constants.CMTMessageCode;
import com.customer.management.tool.dao.impl.UserManagementDaoImpl;
import com.customer.management.tool.impl.CMTGoBackImpl;
import com.customer.management.tool.impl.CMTServiceImpl;
import com.customer.management.tool.pojo.UserDetailHistory;

/**
 *
 * @author Aviral
 */
@Component
@Scope("prototype")
public class GetUser extends CMTServiceImpl implements Serializable {

	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form GetUser
	 */
	@Autowired
	private UserManagementDaoImpl userManagementDaoImpl;
	@Autowired
	private GetUsers getUsers;
	@Autowired
	private ModifyUser modifyUser;
	@Autowired
	private CMTGoBackImpl CMTgoBackImpl;

	public GetUser(ResourceBundleMessageSource resourceBundleMessageSource) {
		initComponents(resourceBundleMessageSource);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @param messageSource
	 */
	private void initComponents(ResourceBundleMessageSource messageSource) {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		username = new javax.swing.JTextField();
		email = new javax.swing.JTextField();
		mobile = new javax.swing.JTextField();
		submit = new javax.swing.JButton();
		getRB = new javax.swing.JRadioButton();
		updateRB = new javax.swing.JRadioButton();
		deleteRB = new javax.swing.JRadioButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBounds(new java.awt.Rectangle(450, 150, 0, 0));
		jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
		jLabel1.setText(messageSource.getMessage(CMTMessageCode.USER_DETAIL.getValue(), null, Locale.getDefault()));

		jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel2.setText(messageSource.getMessage(CMTMessageCode.USERNAME.getValue(), null, Locale.getDefault()));

		jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel3.setText(messageSource.getMessage(CMTMessageCode.EMAIL.getValue(), null, Locale.getDefault()));

		jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel4.setText(messageSource.getMessage(CMTMessageCode.MOBILE.getValue(), null, Locale.getDefault()));

		submit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		submit.setText(messageSource.getMessage(CMTMessageCode.SUBMIT.getValue(), null, Locale.getDefault()));

		submit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				submitActionPerformed(evt);
			}
		});

		buttonGroup1.add(getRB);
		getRB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		getRB.setText(messageSource.getMessage(CMTMessageCode.GET.getValue(), null, Locale.getDefault()));

		buttonGroup1.add(updateRB);
		updateRB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		updateRB.setText(messageSource.getMessage(CMTMessageCode.UPDATE.getValue(), null, Locale.getDefault()));

		buttonGroup1.add(deleteRB);
		deleteRB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		deleteRB.setText(messageSource.getMessage(CMTMessageCode.DELETE.getValue(), null, Locale.getDefault()));

		jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jButton2.setText(messageSource.getMessage(CMTMessageCode.BACK.getValue(), null, Locale.getDefault()));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel1Layout.createSequentialGroup().addGap(49, 49, 49)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(getRB)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel2).addComponent(jLabel3)
																.addComponent(jLabel4).addComponent(jButton2)))
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGap(16, 16, 16).addComponent(updateRB)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(deleteRB).addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		84, Short.MAX_VALUE))
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGap(74, 74, 74).addGroup(jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addComponent(submit).addGap(0,
																						0, Short.MAX_VALUE))
																		.addComponent(email).addComponent(username)
																		.addComponent(mobile))))
												.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(9, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(getRB).addComponent(updateRB).addComponent(deleteRB))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(20, 20, 20)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(21, 21, 21)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(26, 26, 26)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(submit).addComponent(jButton2))
						.addGap(32, 32, 32)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(109, 109, 109).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addGap(34, 34, 34).addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(25, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(13, 13, 13)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(27, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		dispose();
		CMTgoBackImpl.backButtonCode(this);

	}

	private void submitActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			UserDetailHistory userDetail = new UserDetailHistory(0, username.getText(), null, email.getText(),
					mobile.getText(), new Date().toString(), new Date().toString(), null);
			if (getRB.isSelected()) {
				userDetail.setDescription("get");
				userDetail.setStatus("a");
				List<UserDetailHistory> listDetails = userManagementDaoImpl.getUsers(userDetail);
				dispose();
				getUsers.setTitle("User Data");
				getUsers.displayRecords(listDetails);
				getUsers.setVisible(true);
			} else if (updateRB.isSelected()) {
				userDetail.setDescription("update");
				userDetail.setStatus("a");
				UserDetailHistory userDetailResponse = acServiceUserImpl.getUserData(userDetail);
				if (userDetailResponse == null) {
					throw new Exception("Please give correct data to get details");
				}
				dispose();
				modifyUser.setValues(userDetailResponse);
				modifyUser.setTitle("Update");
				modifyUser.setVisible(true);
			} else if (deleteRB.isSelected()) {
				userDetail.setDescription("delete");
				userDetail.setStatus("d");
				String response = acServiceUserImpl.deleteUserData(userDetail);
				JOptionPane.showMessageDialog(new JFrame(), response, response, JOptionPane.INFORMATION_MESSAGE);
			}
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(new JFrame(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}
	}

	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JRadioButton deleteRB;
	private javax.swing.JTextField email;
	private javax.swing.JRadioButton getRB;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField mobile;
	private javax.swing.JButton submit;
	private javax.swing.JRadioButton updateRB;
	private javax.swing.JTextField username;
}
