/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.customer.management.tool.ui.admin;

import java.util.List;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

import com.customer.management.tool.constants.UserManagementCode;
import com.customer.management.tool.impl.CMTServiceImpl;
import com.customer.management.tool.pojo.UserDetailHistory;

/**
 *
 * @author Aviral
 */

@Component
@Scope("prototype")
public class UserManagement extends CMTServiceImpl {

	@Autowired
	private WelcomeForm welcomeForm;

	private List<UserDetailHistory> userDetailHistories;

	public List<UserDetailHistory> getUserDetailHistories() {
		return userDetailHistories;
	}

	public void setUserDetailHistories(List<UserDetailHistory> userDetailHistories) {
		this.userDetailHistories = userDetailHistories;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form UserManagement
	 */
	public UserManagement() {
		String[] items = { UserManagementCode.ACTIVATE.name(), UserManagementCode.DEACTIVATE.name(),
				UserManagementCode.DELETE.name() };
		ComboBoxModel<String> aModel = new DefaultComboBoxModel<String>(items);
		initComponents();
		changeStatus.setModel(aModel);
		update.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		Submit = new javax.swing.JButton();
		back = new javax.swing.JButton();
		update = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		username = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		email = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		mobile = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		changeStatus = new javax.swing.JComboBox();
		search = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTable1.setAutoCreateRowSorter(true);
		jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
		jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] {

		}));
		jTable1.setCellSelectionEnabled(true);
		jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jTable1.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(jTable1);
		jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

		Submit.setText("Submit");
		Submit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SubmitActionPerformed(evt);
			}
		});

		back.setText("Back");
		back.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backActionPerformed(evt);
			}
		});

		update.setText("Update");
		update.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				updateActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
								.addComponent(
										jScrollPane1)
								.addContainerGap())
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(back).addGap(32, 32, 32).addComponent(update).addGap(30, 30, 30)
										.addComponent(Submit).addGap(178, 178, 178)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(Submit).addComponent(back).addComponent(update))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel1.setText("Username");

		jLabel2.setText("Email");

		jLabel3.setText("Mobile");

		jLabel4.setText("Change Status to");

		search.setText("Search");
		search.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGap(19, 19, 19)
														.addComponent(jLabel1).addGap(18, 18, 18)
														.addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE,
																119, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(32, 32, 32).addComponent(jLabel2).addGap(32, 32, 32)
														.addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE,
																117, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(26, 26, 26).addComponent(jLabel3)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(
																mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup().addGap(129, 129, 129)
														.addComponent(jLabel4).addGap(46, 46, 46)
														.addComponent(changeStatus,
																javax.swing.GroupLayout.PREFERRED_SIZE, 134,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(69, 69, 69).addComponent(search)))
												.addGap(0, 26, Short.MAX_VALUE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addGap(22, 22, 22)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1)
								.addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2)
								.addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3).addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4)
								.addComponent(changeStatus, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(search))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(45, 45, 45)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void updateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateActionPerformed

		int selectedRowIndex = jTable1.getSelectedRow();
		if (selectedRowIndex >= 0) {
			UserDetailHistory detailHistory = new UserDetailHistory();
			detailHistory.setName(jTable1.getModel().getValueAt(selectedRowIndex, 1).toString());
			detailHistory.setEmail(jTable1.getModel().getValueAt(selectedRowIndex, 2).toString());
			detailHistory.setMobile(jTable1.getModel().getValueAt(selectedRowIndex, 3).toString());
			if (getUserDetailHistories() != null && !getUserDetailHistories().isEmpty()) {
				if (getUserDetailHistories().size() == 1) {
					detailHistory.setUsername(getUserDetailHistories().get(0).getUsername());
					detailHistory.setUserId(getUserDetailHistories().get(0).getUserId());
				} else {
					detailHistory.setUsername(getUserDetailHistories().get(selectedRowIndex).getUsername());
					detailHistory.setUserId(getUserDetailHistories().get(selectedRowIndex).getUserId());
				}
				try {
					String response = acServiceUserImpl.updateUserData(detailHistory);
					JOptionPane.showMessageDialog(new JFrame(), response, "Error", JOptionPane.INFORMATION_MESSAGE);
				} catch (Exception e) {
					JOptionPane.showMessageDialog(new JFrame(), "Something went wrong, try again", "Error",
							JOptionPane.INFORMATION_MESSAGE);
				}
			}
		} else {
			JOptionPane.showMessageDialog(new JFrame(), "Please Select atleast one Row", "Error",
					JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_updateActionPerformed

	private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SubmitActionPerformed

		try {
			int selectedRowIndex = jTable1.getSelectedRow();
			if (selectedRowIndex >= 0) {
				UserDetailHistory detailHistory = new UserDetailHistory();
				detailHistory.setUsername(jTable1.getModel().getValueAt(selectedRowIndex, 0).toString());
				detailHistory.setEmail(jTable1.getModel().getValueAt(selectedRowIndex, 3).toString());
				detailHistory.setMobile(jTable1.getModel().getValueAt(selectedRowIndex, 4).toString());
				if (changeStatus.getSelectedItem().toString().equals(UserManagementCode.ACTIVATE.toString())) {
					detailHistory.setStatus(UserManagementCode.ACTIVATE.getPrperty());
				} else if (changeStatus.getSelectedItem().toString().equals(UserManagementCode.DEACTIVATE.toString())) {
					detailHistory.setStatus(UserManagementCode.DEACTIVATE.getPrperty());
				} else {
					detailHistory.setStatus(UserManagementCode.DELETE.getPrperty());
				}

				String response = acServiceUserImpl.activateDeactivateUser(detailHistory);
				System.out.println(response);
			} else {
				JOptionPane.showMessageDialog(new JFrame(), "Please Select atleast one Row", "Error",
						JOptionPane.ERROR_MESSAGE);
			}
		} catch (Exception ex) {
			if (ex instanceof ArrayIndexOutOfBoundsException) {
				JOptionPane.showMessageDialog(new JFrame(), "Please Select atleast one Row", "Error",
						JOptionPane.ERROR_MESSAGE);
			} else {
				ex.printStackTrace();
			}
		}
	}// GEN-LAST:event_SubmitActionPerformed

	private void backActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backActionPerformed

		dispose();
		welcomeForm.setVisible(true);
		welcomeForm.setTitle("Welcome Form");
	}// GEN-LAST:event_backActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

		UserDetailHistory detailHistory = new UserDetailHistory();
		detailHistory.setUsername(username.getText());
		detailHistory.setEmail(email.getText());
		detailHistory.setMobile(mobile.getText());
		if (changeStatus.getSelectedItem().toString().equals(UserManagementCode.ACTIVATE.toString())) {
			detailHistory.setStatus(UserManagementCode.ACTIVATE.getPrperty());
		} else if (changeStatus.getSelectedItem().toString().equals(UserManagementCode.DEACTIVATE.toString())) {
			detailHistory.setStatus(UserManagementCode.DEACTIVATE.getPrperty());
		} else {
			detailHistory.setStatus(UserManagementCode.DELETE.getPrperty());
		}

		List<UserDetailHistory> userDetailHistory = acServiceUserImpl.getUser(detailHistory);
		if (!StringUtils.isEmpty(userDetailHistory) && !userDetailHistory.isEmpty()) {
			this.setUserDetailHistories(userDetailHistory);
			display(userDetailHistory);
		} else {
			JOptionPane.showMessageDialog(new JFrame(), "No Data Found", "Error", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	public void display(List<UserDetailHistory> userDetailHistory) {

		DefaultTableModel model = new DefaultTableModel();
		model.setColumnIdentifiers(new Object[] { "Username", "Name", "Email", "Mobile", "Status" });

		// boolean[] canEdit = new boolean[] { false, false, true, true, true,
		// true };

		for (UserDetailHistory detailHistory : userDetailHistory)
			model.addRow(new Object[] { detailHistory.getUsername(), detailHistory.getName(), detailHistory.getEmail(),
					detailHistory.getMobile(), detailHistory.getStatus() });
		jTable1.setModel(model);
		// jTable1.setEnabled(false);
		jTable1.setRowSelectionAllowed(true);
		jTable1.setCellSelectionEnabled(false);
		jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

		// selectionTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		model.fireTableDataChanged();
		// dataChanged(model);
	}

	public void updateContent() {

		this.setVisible(true);
		this.setTitle("Update");
		this.Submit.setVisible(false);
		this.update.setVisible(true);
	}

	public void getContent() {

		this.setVisible(true);
		this.Submit.setVisible(false);
		this.update.setVisible(false);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton Submit;
	private javax.swing.JButton back;
	private javax.swing.JComboBox<String> changeStatus;
	private javax.swing.JTextField email;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField mobile;
	private javax.swing.JButton search;
	private javax.swing.JButton update;
	private javax.swing.JTextField username;
	// End of variables declaration//GEN-END:variables
}
