/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.customer.management.tool.ui.customer;

import java.util.List;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.customer.management.tool.impl.CMTGoBackImpl;
import com.customer.management.tool.impl.CMTServiceImpl;
import com.customer.management.tool.pojo.CustomerJobDetail;

/**
 *
 * @author Aviral
 */

@Component
@Scope("prototype")
public class CustomerHistory extends CMTServiceImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Autowired
	private AddCustomerRepairDetail addRepairDetails;
	@Autowired
	private CMTGoBackImpl acServiceGoBackImpl;

	/**
	 * Creates new form CustomerHistory
	 */
	public CustomerHistory() {
		initComponents();
	}

	public void displayContent(List<CustomerJobDetail> reparingDetails) {

		DefaultTableModel model = new DefaultTableModel();
		model.setColumnIdentifiers(new Object[] { "CustomerID", "Name", "Description", "Actual Amount", "Paid Amount",
				"Work Date", "Model No", "Warrenty Upto", "Warranty Expired" });
		for (CustomerJobDetail reparingDetail : reparingDetails) {
			model.addRow(new Object[] { reparingDetail.getCustomerId(), /*reparingDetail.getName(),*/
					reparingDetail.getDescription(), reparingDetail.getActualAmount(), reparingDetail.getPaidAmount(),
					reparingDetail.getUpdateDate(), /*reparingDetail.getModel_Vehicle(),*/ reparingDetail.getWarranty(),
					reparingDetail.getIsWarrantyExpired() });
		}

		if (jTable1.getModel().getRowCount() > 0) {
			initComponents();
		}
		model.fireTableDataChanged();
		jTable1.setModel(model);

		jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			@Override
			public void valueChanged(ListSelectionEvent e) {
				CustomerJobDetail reparingDetail = new CustomerJobDetail();
				reparingDetail
						.setCustomerId(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
//				reparingDetail.setName(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
				dispose();
//				addRepairDetails.setCustomerID(reparingDetail);
				addRepairDetails.setVisible(true);

			}
		});

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer Previous Record");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	private void refreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_refreshActionPerformed

	}// GEN-LAST:event_refreshActionPerformed
	
	private void backActionPerformed(java.awt.event.ActionEvent evt){
		
		dispose();
		acServiceGoBackImpl.backButtonCode(this);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
